run:
	python3 main.py
	
delete:
	rm -f 1/UnspentTransactions.txt
	rm -f 1/SpentTransactions.txt
	rm -f 1/log.json
	rm -f 2/UnspentTransactions.txt
	rm -f 2/SpentTransactions.txt
	rm -f 2/log.json
	rm -f 3/UnspentTransactions.txt
	rm -f 3/SpentTransactions.txt
	rm -f 3/log.json
	rm -rf __pycache__/